#!/bin/bash

BASEDIR=$(dirname "$0")
LICENSER="go run ${BASEDIR}/../main.go"

SUCCESS=true

# Ensure Licenses are present
if ${LICENSER} verify -r .; then
    echo "Licenses are present on all recognised files."
else
    echo "Licenses are missing."
    SUCCESS=false
fi

if go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2 run; then
    echo "golangci-lint succeded."
else
    echo "golangci-lint failed."
    SUCCESS=false
fi

if [ "$SUCCESS" = false ] ; then
    echo "One or more linters failed."
    exit 1
else
    echo "All linters passed!"
fi
